In [19]:
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn  # All neural network modules, nn.Linear, nn.Conv2d, BatchNorm, Loss functions
import torch.optim as optim  # For all Optimization algorithms, SGD, Adam, etc.
import torch.nn.functional as F  # All functions that don't have any parameters
from torch.utils.data import (DataLoader)  # Gives easier dataset managment and creates mini batches
#import torchvision  # torch package for vision related things
#import torchvision.datasets as datasets  # Has standard datasets we can import in a nice way
#import torchvision.transforms as transforms
import pandas as pd
import random
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, make_scorer
from tqdm.auto import tqdm
from transformers import DistilBertTokenizer

In [20]:
# Run when executing on Google Colab
#from google.colab import drive
#drive.mount('/content/drive')

#!cp "/content/drive/MyDrive/Colab Notebooks/Deep Learning/DeepLProject/SpamDataset.zip" "./SpamDataset.zip"
#!unzip SpamDataset.zip

In [21]:
# Split the downloaded Youtube01-Psy.csv file into train, validation and test sets
data = pd.read_csv('SpamDataset/Youtube05-Combined.csv')
# data = pd.read_csv('TSwift_ShakeItOff_Spam.csv')
data = data.sample(frac=1).reset_index(drop=True)  # Shuffle the data
train_data = data[:int(0.7*len(data))]
val_data = data[int(0.7*len(data)):int(0.85*len(data))]
test_data = data[int(0.85*len(data)):]

# Tokenize the data using distillbert
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')

# Turn pd dataframe into a tokenized PyTorch dataset that DataLoader can use via the SpamDataset class
class SpamDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        row = self.data.iloc[idx]
        comment_tokens = row['CONTENT']
        label = row['CLASS']
        return comment_tokens, label
    
    def collate_fn(self, batch):
        comments = [row[0] for row in batch]
        labels = [row[1] for row in batch]
        tokens = tokenizer.batch_encode_plus(comments, truncation=True, padding='max_length', max_length=30, return_tensors='pt')
        return tokens, torch.tensor(labels)
    
train_dataset = SpamDataset(train_data)
val_dataset = SpamDataset(val_data)
test_dataset = SpamDataset(test_data)


# Load Data and collate it
batch_size = 64
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, collate_fn=train_dataset.collate_fn)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=True, collate_fn=val_dataset.collate_fn)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True, collate_fn=test_dataset.collate_fn)

In [22]:
# Print a random sample from the train_loader to confirm correct loading and tokenization
sample = next(iter(train_loader))
print(sample)
print([samples.size() for samples in sample[0]['input_ids']])


({'input_ids': tensor([[  101,  2065,  1996,  ...,     0,     0,     0],
        [  101, 16770,  1024,  ...,     0,     0,     0],
        [  101,  7632,   999,  ...,     0,     0,     0],
        ...,
        [  101,  1008,  1008,  ...,  2026,  2047,   102],
        [  101,  4931,   999,  ...,     0,     0,     0],
        [  101,  1045,  2293,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}, tensor([0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0]))
[torch.Size([30]), torch.Size([30]), torch.Size([30]), torch.Size([30]), torch.Size([30]), torch.Size([30]), torch.Size([30]), torch.Size([30]), torch.Size([30]), tor

# Models
Create all different Models that we are testing. Most have LSTMs in common, but 2 add improvements

In [23]:
# Recurrent neural network with LSTM (many-to-one) for sequence classification to produce a binary output
## The network includes an Embedding layer, an LSTM layer and a Linear layer
class RNN_LSTM(nn.Module):
    def __init__(self, embedding_dict, embedding_size, hidden_size, num_layers, num_classes, dropout):
        super(RNN_LSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.embedding = nn.Embedding(embedding_dict, embedding_size)
        self.lstm = nn.LSTM(embedding_size, hidden_size, num_layers, batch_first=True, dropout=dropout)
        self.fc = nn.Linear(hidden_size, num_classes)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # x: (batch_size, max_seq_length)
        embedding = self.dropout(self.embedding(x))
        # embedding shape: (batch_size, max_seq_length, embedding_size)
        output, (h_n, c_n) = self.lstm(embedding)
        # output shape: (batch_size, max_seq_length, hidden_size)
        # h_n shape: (num_layers, batch_size, hidden_size)
        out = self.fc(h_n[-1, :, :])
        # out shape: (batch_size, num_classes)
        return out
    
# Bidirectional LSTM network for sequence classification to produce a binary output
## The network includes an Embedding layer, a Bidirectional LSTM layer and a Linear layer
class BiLSTM(nn.Module):
    def __init__(self, embedding_dict, embedding_size, hidden_size, num_layers, num_classes, dropout):
        super(BiLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.embedding = nn.Embedding(embedding_dict, embedding_size)
        self.dropout = nn.Dropout(dropout)
        self.lstm = nn.LSTM(embedding_size, hidden_size, num_layers, batch_first=True, dropout=dropout, bidirectional=True)
        self.fc = nn.Linear(hidden_size*2, num_classes)
        

    def forward(self, x):
        # x: (batch_size, max_seq_length)
        embedding = self.dropout(self.embedding(x))
        # embedding shape: (batch_size, max_seq_length, embedding_size)
        output, (h_n, c_n) = self.lstm(embedding)
        # output shape: (batch_size, max_seq_length, hidden_size*2)
        # h_n shape: (num_layers*2, batch_size, hidden_size)
        out = self.fc(torch.cat((h_n[-2, :, :], h_n[-1, :, :]), dim=1))
        # out shape: (batch_size, num_classes)
        return out

# An Attention-LSTM network for sequence classification to produce a binary output
## The network includes an Embedding layer, an Attention layer, an LSTM layer and a Linear layer
class AttentionLSTM(nn.Module):
    def __init__(self, embedding_dict, embedding_size, hidden_size, num_layers, num_classes, dropout):
        super(AttentionLSTM, self).__init__()
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.embedding = nn.Embedding(embedding_dict, embedding_size)
        self.dropout = nn.Dropout(dropout)
        self.lstm = nn.LSTM(embedding_size, hidden_size, num_layers, batch_first=True, dropout=dropout)
        self.attention = nn.Linear(hidden_size, 1)
        self.fc = nn.Linear(hidden_size, num_classes)
        
    def forward(self, x):
        # x: (batch_size, max_seq_length)
        embedding = self.dropout(self.embedding(x))
        # embedding shape: (batch_size, max_seq_length, embedding_size)
        output, (h_n, c_n) = self.lstm(embedding)
        # output shape: (batch_size, max_seq_length, hidden_size)
        # h_n shape: (num_layers, batch_size, hidden_size)
        attention_weights = F.softmax(self.attention(output), dim=1)
        # attention_weights shape: (batch_size, max_seq_length, 1)
        out = torch.sum(attention_weights * output, dim=1)
        # out shape: (batch_size, hidden_size)
        out = self.fc(out)
        # out shape: (batch_size, num_classes)
        return out

In [24]:
# Store all the predictions in model_predictions and the actual labels in actual_labels
tokens = []
original_comments = []
model_predictions = []
actual_labels = []

# Validation
def check_accuracy(loader, model):
    num_correct = 0
    num_samples = 0
    total_loss = 0.0
    predictions = []
    targets = []
    model.eval()

    with torch.no_grad():
        for data, target in loader:
            data = {key: value.to(device) for key, value in data.items()}
            target = target.to(device)

            scores = model(data['input_ids'])
            _, predicted = scores.max(1)
            # Store decoded original comments, model predictions and actual labels 
            original_comments.extend([tokenizer.decode(data['input_ids'][i]) for i in range(len(data['input_ids']))])
            tokens.extend(data['input_ids'])
            model_predictions.extend(predicted)
            actual_labels.extend(target)
            num_correct += (predicted == target).sum()
            num_samples += predicted.size(0)

            loss = criterion(scores, target)
            total_loss += loss


            predictions.extend(predicted.tolist())
            targets.extend(target.tolist())

    # model.train()
    average_loss = total_loss / num_samples
    accuracy = num_correct/num_samples
    return accuracy, predictions, targets, average_loss

In [25]:
def results(model):
    train_acc, train_preds, train_targets, train_loss = check_accuracy(train_loader, model)
    val_acc, val_preds, val_targets, train_loss = check_accuracy(val_loader, model)
    test_acc, test_preds, test_targets, train_loss = check_accuracy(test_loader, model)

    print(f'Train accuracy: {train_acc}')
    print(f'Validation accuracy: {val_acc}')
    print(f'Test accuracy: {test_acc}')

    train_cm = confusion_matrix(train_targets, train_preds)
    val_cm = confusion_matrix(val_targets, val_preds)
    test_cm = confusion_matrix(test_targets, test_preds)

    print(f'Train Confusion Matrix:\n{train_cm}')
    print(f'Validation Confusion Matrix:\n{val_cm}')
    print(f'Test Confusion Matrix:\n{test_cm}')

    # Classification report
    train_report = classification_report(train_targets, train_preds)
    val_report = classification_report(val_targets, val_preds)
    test_report = classification_report(test_targets, test_preds)

    print(f'Train Classification Report:\n{train_report}')
    print(f'Validation Classification Report:\n{val_report}')
    print(f'Test Classification Report:\n{test_report}')

# Training

In [26]:
# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
criterion = nn.CrossEntropyLoss()

# Set the hyperparameters for all the models     # TODO: analyze these by model
embedding_dict = tokenizer.vocab_size
embedding_size = 128
hidden_size = 256
NUM_LAYERS = [2,4,8,16,32,64]
num_classes = 2
DROPOUT = [0.3, 0.5, 0.7]
LR = [0.001, 0.003, 0.005, 0.007, 0.009]
NUM_EPOCH = [10, 25, 50]
# init LSTM model

for num_layers in NUM_LAYERS:
    for dropout in DROPOUT:
        for learning_rate in LR:
            for num_epochs in NUM_EPOCH:
                model_LSTM = RNN_LSTM(embedding_dict, embedding_size, hidden_size, num_layers, num_classes, dropout).to(device)
                optimizer_LSTM = optim.Adam(model_LSTM.parameters(), lr=learning_rate)
                # RNN_LSTM
                print('RNN_LSTM Training')
                for epoch in range(num_epochs):
                    model_LSTM.train()
                    loop = tqdm(enumerate(train_loader), total=len(train_loader), leave=False)
                    for batch_idx, (data, targets) in loop:
                        data = {key: value.to(device) for key, value in data.items()}
                        targets = targets.to(device)
                        # forward
                        scores = model_LSTM(data['input_ids'])
                        loss = criterion(scores, targets)
                        # backward
                        optimizer_LSTM.zero_grad()
                        loss.backward()
                        # gradient descent or adam step
                        optimizer_LSTM.step()
                        # update progress bar
                        loop.set_description(f'Epoch [{epoch}/{num_epochs}]')
                        loop.set_postfix(loss=loss.item())
                # init BiLSTM model
                model_BiLSTM = BiLSTM(embedding_dict, embedding_size, hidden_size, num_layers, num_classes, dropout).to(device)
                optimizer_BiLSTM = optim.Adam(model_BiLSTM.parameters(), lr=learning_rate)
                # BiLSTM
                print('BiLSTM Training')
                for epoch in range(num_epochs):
                    model_BiLSTM.train()
                    loop = tqdm(enumerate(train_loader), total=len(train_loader), leave=False)
                    for batch_idx, (data, targets) in loop:
                        data = {key: value.to(device) for key, value in data.items()}
                        targets = targets.to(device)
                        # forward
                        scores = model_BiLSTM(data['input_ids'])
                        loss = criterion(scores, targets)
                        # backward
                        optimizer_BiLSTM.zero_grad()
                        loss.backward()
                        # gradient descent or adam step
                        optimizer_BiLSTM.step()
                        # update progress bar
                        loop.set_description(f'Epoch [{epoch}/{num_epochs}]')
                        loop.set_postfix(loss=loss.item())

                # init AttentionLSTM model
                model_AttentionLSTM = AttentionLSTM(embedding_dict, embedding_size, hidden_size, num_layers, num_classes, dropout).to(device)
                optimizer_AttentionLSTM = optim.Adam(model_AttentionLSTM.parameters(), lr=learning_rate)

                # AttentionLSTM
                print('AttentionLSTM Training')
                for epoch in range(num_epochs):
                    model_AttentionLSTM.train()
                    loop = tqdm(enumerate(train_loader), total=len(train_loader), leave=False)
                    for batch_idx, (data, targets) in loop:
                        data = {key: value.to(device) for key, value in data.items()}
                        targets = targets.to(device)
                        # forward
                        scores = model_AttentionLSTM(data['input_ids'])
                        loss = criterion(scores, targets)
                        # backward
                        optimizer_AttentionLSTM.zero_grad()
                        loss.backward()
                        # gradient descent or adam step
                        optimizer_AttentionLSTM.step()
                        # update progress bar
                        loop.set_description(f'Epoch [{epoch}/{num_epochs}]')
                        loop.set_postfix(loss=loss.item())
                print("Current Num_Layers: ", num_layers)
                print("Current Dropout: ", dropout)
                print("Current Learning Rate: ", learning_rate)
                print("Current Num_Epochs: ", num_epochs)
                results(model_LSTM)
                results(model_BiLSTM)
                results(model_AttentionLSTM)

RNN_LSTM Training


  0%|          | 0/22 [00:00<?, ?it/s]

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.001
Current Num_Epochs:  10
Train accuracy: 0.9408327341079712
Validation accuracy: 0.9112628102302551
Test accuracy: 0.8809523582458496
Train Confusion Matrix:
[[600  61]
 [ 20 688]]
Validation Confusion Matrix:
[[124  17]
 [  9 143]]
Test Confusion Matrix:
[[121  28]
 [  7 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.91      0.94       661
           1       0.92      0.97      0.94       708

    accuracy                           0.94      1369
   macro avg       0.94      0.94      0.94      1369
weighted avg       0.94      0.94      0.94      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.88      0.91       141
           1       0.89      0.94      0.92       152

    accuracy                           0.91       293
   macro avg       0.91      0.91      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.001
Current Num_Epochs:  25
Train accuracy: 0.9934258460998535
Validation accuracy: 0.9249146580696106
Test accuracy: 0.9013605713844299
Train Confusion Matrix:
[[658   3]
 [  6 702]]
Validation Confusion Matrix:
[[129  12]
 [ 10 142]]
Test Confusion Matrix:
[[129  20]
 [  9 136]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       661
           1       1.00      0.99      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       141
           1       0.92      0.93      0.93       152

    accuracy                           0.92       293
   macro avg       0.93      0.92      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.001
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.9556313753128052
Test accuracy: 0.9387755393981934
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[134   7]
 [  6 146]]
Test Confusion Matrix:
[[140   9]
 [  9 136]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.95      0.95       141
           1       0.95      0.96      0.96       152

    accuracy                           0.96       293
   macro avg       0.96      0.96      0.96       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.003
Current Num_Epochs:  10
Train accuracy: 0.9919649362564087
Validation accuracy: 0.9419795274734497
Test accuracy: 0.9353741407394409
Train Confusion Matrix:
[[657   4]
 [  7 701]]
Validation Confusion Matrix:
[[130  11]
 [  6 146]]
Test Confusion Matrix:
[[136  13]
 [  6 139]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       661
           1       0.99      0.99      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       141
           1       0.93      0.96      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.94      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.003
Current Num_Epochs:  25
Train accuracy: 0.9992695450782776
Validation accuracy: 0.9453924894332886
Test accuracy: 0.9319728016853333
Train Confusion Matrix:
[[661   0]
 [  1 707]]
Validation Confusion Matrix:
[[137   4]
 [ 12 140]]
Test Confusion Matrix:
[[144   5]
 [ 15 130]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.97      0.94       141
           1       0.97      0.92      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.003
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.9453924894332886
Test accuracy: 0.9387755393981934
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[130  11]
 [  5 147]]
Test Confusion Matrix:
[[139  10]
 [  8 137]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       141
           1       0.93      0.97      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.94      0.95       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.005
Current Num_Epochs:  10
Train accuracy: 0.9956172108650208
Validation accuracy: 0.9419795274734497
Test accuracy: 0.9149659872055054
Train Confusion Matrix:
[[661   0]
 [  6 702]]
Validation Confusion Matrix:
[[135   6]
 [ 11 141]]
Test Confusion Matrix:
[[137  12]
 [ 13 132]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       661
           1       1.00      0.99      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.96      0.94       141
           1       0.96      0.93      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.94      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.005
Current Num_Epochs:  25
Train accuracy: 0.9992695450782776
Validation accuracy: 0.9283276200294495
Test accuracy: 0.918367326259613
Train Confusion Matrix:
[[660   1]
 [  0 708]]
Validation Confusion Matrix:
[[125  16]
 [  5 147]]
Test Confusion Matrix:
[[130  19]
 [  5 140]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.89      0.92       141
           1       0.90      0.97      0.93       152

    accuracy                           0.93       293
   macro avg       0.93      0.93      0

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.005
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.935153603553772
Test accuracy: 0.9285714030265808
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[126  15]
 [  4 148]]
Test Confusion Matrix:
[[134  15]
 [  6 139]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.89      0.93       141
           1       0.91      0.97      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.93      0.93       293
w

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.007
Current Num_Epochs:  10
Train accuracy: 0.9773557186126709
Validation accuracy: 0.8976109027862549
Test accuracy: 0.9251700639724731
Train Confusion Matrix:
[[661   0]
 [ 31 677]]
Validation Confusion Matrix:
[[133   8]
 [ 22 130]]
Test Confusion Matrix:
[[145   4]
 [ 18 127]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       661
           1       1.00      0.96      0.98       708

    accuracy                           0.98      1369
   macro avg       0.98      0.98      0.98      1369
weighted avg       0.98      0.98      0.98      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.94      0.90       141
           1       0.94      0.86      0.90       152

    accuracy                           0.90       293
   macro avg       0.90      0.90      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.007
Current Num_Epochs:  25
Train accuracy: 1.0
Validation accuracy: 0.9215016961097717
Test accuracy: 0.9217687249183655
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[127  14]
 [  9 143]]
Test Confusion Matrix:
[[136  13]
 [ 10 135]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.90      0.92       141
           1       0.91      0.94      0.93       152

    accuracy                           0.92       293
   macro avg       0.92      0.92      0.92       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.007
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.935153603553772
Test accuracy: 0.9387755393981934
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[129  12]
 [  7 145]]
Test Confusion Matrix:
[[138  11]
 [  7 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.91      0.93       141
           1       0.92      0.95      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.93      0.93       293
w

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.009
Current Num_Epochs:  10
Train accuracy: 0.9985390901565552
Validation accuracy: 0.9522184133529663
Test accuracy: 0.9353741407394409
Train Confusion Matrix:
[[661   0]
 [  2 706]]
Validation Confusion Matrix:
[[136   5]
 [  9 143]]
Test Confusion Matrix:
[[141   8]
 [ 11 134]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       141
           1       0.97      0.94      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.009
Current Num_Epochs:  25
Train accuracy: 1.0
Validation accuracy: 0.9522184133529663
Test accuracy: 0.9149659872055054
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[131  10]
 [  4 148]]
Test Confusion Matrix:
[[135  14]
 [ 11 134]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.93      0.95       141
           1       0.94      0.97      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      0.95       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.3
Current Learning Rate:  0.009
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.935153603553772
Test accuracy: 0.9285714030265808
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[128  13]
 [  6 146]]
Test Confusion Matrix:
[[135  14]
 [  7 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.91      0.93       141
           1       0.92      0.96      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.93      0.93       293
w

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.001
Current Num_Epochs:  10
Train accuracy: 0.9065011143684387
Validation accuracy: 0.894197940826416
Test accuracy: 0.8979591727256775
Train Confusion Matrix:
[[593  68]
 [ 60 648]]
Validation Confusion Matrix:
[[127  14]
 [ 17 135]]
Test Confusion Matrix:
[[128  21]
 [  9 136]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.90      0.90       661
           1       0.91      0.92      0.91       708

    accuracy                           0.91      1369
   macro avg       0.91      0.91      0.91      1369
weighted avg       0.91      0.91      0.91      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.90      0.89       141
           1       0.91      0.89      0.90       152

    accuracy                           0.89       293
   macro avg       0.89      0.89      0

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.001
Current Num_Epochs:  25
Train accuracy: 0.9883126616477966
Validation accuracy: 0.9522184133529663
Test accuracy: 0.9353741407394409
Train Confusion Matrix:
[[658   3]
 [ 13 695]]
Validation Confusion Matrix:
[[135   6]
 [  8 144]]
Test Confusion Matrix:
[[137  12]
 [  7 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       661
           1       1.00      0.98      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.96      0.95       141
           1       0.96      0.95      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.001
Current Num_Epochs:  50
Train accuracy: 0.9985390901565552
Validation accuracy: 0.9317406415939331
Test accuracy: 0.9353741407394409
Train Confusion Matrix:
[[661   0]
 [  2 706]]
Validation Confusion Matrix:
[[132   9]
 [ 11 141]]
Test Confusion Matrix:
[[142   7]
 [ 12 133]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.94      0.93       141
           1       0.94      0.93      0.93       152

    accuracy                           0.93       293
   macro avg       0.93      0.93      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.003
Current Num_Epochs:  10
Train accuracy: 0.989043116569519
Validation accuracy: 0.935153603553772
Test accuracy: 0.9081632494926453
Train Confusion Matrix:
[[649  12]
 [  3 705]]
Validation Confusion Matrix:
[[126  15]
 [  4 148]]
Test Confusion Matrix:
[[128  21]
 [  6 139]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.98      0.99       661
           1       0.98      1.00      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.97      0.89      0.93       141
           1       0.91      0.97      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.93      0.

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.003
Current Num_Epochs:  25
Train accuracy: 0.9985390901565552
Validation accuracy: 0.935153603553772
Test accuracy: 0.9081632494926453
Train Confusion Matrix:
[[660   1]
 [  1 707]]
Validation Confusion Matrix:
[[131  10]
 [  9 143]]
Test Confusion Matrix:
[[132  17]
 [ 10 135]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.93      0.93       141
           1       0.93      0.94      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.93      0

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.003
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.9419795274734497
Test accuracy: 0.9319728016853333
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[129  12]
 [  5 147]]
Test Confusion Matrix:
[[137  12]
 [  8 137]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       141
           1       0.92      0.97      0.95       152

    accuracy                           0.94       293
   macro avg       0.94      0.94      0.94       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.005
Current Num_Epochs:  10
Train accuracy: 0.9941563010215759
Validation accuracy: 0.9385665655136108
Test accuracy: 0.942176878452301
Train Confusion Matrix:
[[658   3]
 [  5 703]]
Validation Confusion Matrix:
[[132   9]
 [  9 143]]
Test Confusion Matrix:
[[141   8]
 [  9 136]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       661
           1       1.00      0.99      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       141
           1       0.94      0.94      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.94      0

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.005
Current Num_Epochs:  25
Train accuracy: 1.0
Validation accuracy: 0.9488054513931274
Test accuracy: 0.9557822942733765
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[137   4]
 [ 11 141]]
Test Confusion Matrix:
[[146   3]
 [ 10 135]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.97      0.95       141
           1       0.97      0.93      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      0.95       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.005
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.9419795274734497
Test accuracy: 0.9455782175064087
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[129  12]
 [  5 147]]
Test Confusion Matrix:
[[139  10]
 [  6 139]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.91      0.94       141
           1       0.92      0.97      0.95       152

    accuracy                           0.94       293
   macro avg       0.94      0.94      0.94       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.007
Current Num_Epochs:  10
Train accuracy: 0.9861212372779846
Validation accuracy: 0.9522184133529663
Test accuracy: 0.9319728016853333
Train Confusion Matrix:
[[656   5]
 [ 14 694]]
Validation Confusion Matrix:
[[133   8]
 [  6 146]]
Test Confusion Matrix:
[[139  10]
 [ 10 135]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       661
           1       0.99      0.98      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       141
           1       0.95      0.96      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.007
Current Num_Epochs:  25
Train accuracy: 1.0
Validation accuracy: 0.9317406415939331
Test accuracy: 0.9251700639724731
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[130  11]
 [  9 143]]
Test Confusion Matrix:
[[137  12]
 [ 10 135]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       141
           1       0.93      0.94      0.93       152

    accuracy                           0.93       293
   macro avg       0.93      0.93      0.93       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.007
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.9317406415939331
Test accuracy: 0.9149659872055054
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[129  12]
 [  8 144]]
Test Confusion Matrix:
[[130  19]
 [  6 139]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.91      0.93       141
           1       0.92      0.95      0.94       152

    accuracy                           0.93       293
   macro avg       0.93      0.93      0.93       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.009
Current Num_Epochs:  10
Train accuracy: 0.9970781803131104
Validation accuracy: 0.9453924894332886
Test accuracy: 0.9489796161651611
Train Confusion Matrix:
[[661   0]
 [  4 704]]
Validation Confusion Matrix:
[[137   4]
 [ 12 140]]
Test Confusion Matrix:
[[145   4]
 [ 11 134]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       661
           1       1.00      0.99      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.97      0.94       141
           1       0.97      0.92      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.009
Current Num_Epochs:  25
Train accuracy: 1.0
Validation accuracy: 0.9522184133529663
Test accuracy: 0.9251700639724731
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[134   7]
 [  7 145]]
Test Confusion Matrix:
[[132  17]
 [  5 140]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95       141
           1       0.95      0.95      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      0.95       293


BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.5
Current Learning Rate:  0.009
Current Num_Epochs:  50
Train accuracy: 1.0
Validation accuracy: 0.935153603553772
Test accuracy: 0.9319728016853333
Train Confusion Matrix:
[[661   0]
 [  0 708]]
Validation Confusion Matrix:
[[127  14]
 [  5 147]]
Test Confusion Matrix:
[[134  15]
 [  5 140]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.90      0.93       141
           1       0.91      0.97      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.93      0.93       293
w

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.001
Current Num_Epochs:  10
Train accuracy: 0.8970051407814026
Validation accuracy: 0.8907849788665771
Test accuracy: 0.8809523582458496
Train Confusion Matrix:
[[644  17]
 [124 584]]
Validation Confusion Matrix:
[[135   6]
 [ 26 126]]
Test Confusion Matrix:
[[137  12]
 [ 23 122]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.97      0.90       661
           1       0.97      0.82      0.89       708

    accuracy                           0.90      1369
   macro avg       0.91      0.90      0.90      1369
weighted avg       0.91      0.90      0.90      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.96      0.89       141
           1       0.95      0.83      0.89       152

    accuracy                           0.89       293
   macro avg       0.90      0.89      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.001
Current Num_Epochs:  25
Train accuracy: 0.9437545537948608
Validation accuracy: 0.9249146580696106
Test accuracy: 0.9319728016853333
Train Confusion Matrix:
[[640  21]
 [ 56 652]]
Validation Confusion Matrix:
[[131  10]
 [ 12 140]]
Test Confusion Matrix:
[[136  13]
 [  7 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.97      0.94       661
           1       0.97      0.92      0.94       708

    accuracy                           0.94      1369
   macro avg       0.94      0.94      0.94      1369
weighted avg       0.95      0.94      0.94      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.93      0.92       141
           1       0.93      0.92      0.93       152

    accuracy                           0.92       293
   macro avg       0.92      0.93      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.001
Current Num_Epochs:  50
Train accuracy: 0.9861212372779846
Validation accuracy: 0.9249146580696106
Test accuracy: 0.918367326259613
Train Confusion Matrix:
[[649  12]
 [  7 701]]
Validation Confusion Matrix:
[[124  17]
 [  5 147]]
Test Confusion Matrix:
[[128  21]
 [  3 142]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       661
           1       0.98      0.99      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.88      0.92       141
           1       0.90      0.97      0.93       152

    accuracy                           0.92       293
   macro avg       0.93      0.92      0

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.003
Current Num_Epochs:  10
Train accuracy: 0.9298758506774902
Validation accuracy: 0.9215016961097717
Test accuracy: 0.9013605713844299
Train Confusion Matrix:
[[659   2]
 [ 94 614]]
Validation Confusion Matrix:
[[139   2]
 [ 21 131]]
Test Confusion Matrix:
[[141   8]
 [ 21 124]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.88      1.00      0.93       661
           1       1.00      0.87      0.93       708

    accuracy                           0.93      1369
   macro avg       0.94      0.93      0.93      1369
weighted avg       0.94      0.93      0.93      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.99      0.92       141
           1       0.98      0.86      0.92       152

    accuracy                           0.92       293
   macro avg       0.93      0.92      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.003
Current Num_Epochs:  25
Train accuracy: 0.989043116569519
Validation accuracy: 0.9419795274734497
Test accuracy: 0.9523809552192688
Train Confusion Matrix:
[[655   6]
 [  9 699]]
Validation Confusion Matrix:
[[130  11]
 [  6 146]]
Test Confusion Matrix:
[[140   9]
 [  5 140]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       661
           1       0.99      0.99      0.99       708

    accuracy                           0.99      1369
   macro avg       0.99      0.99      0.99      1369
weighted avg       0.99      0.99      0.99      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.92      0.94       141
           1       0.93      0.96      0.94       152

    accuracy                           0.94       293
   macro avg       0.94      0.94      0

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.003
Current Num_Epochs:  50
Train accuracy: 0.9978086352348328
Validation accuracy: 0.9556313753128052
Test accuracy: 0.9285714030265808
Train Confusion Matrix:
[[658   3]
 [  0 708]]
Validation Confusion Matrix:
[[133   8]
 [  5 147]]
Test Confusion Matrix:
[[135  14]
 [  7 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       141
           1       0.95      0.97      0.96       152

    accuracy                           0.96       293
   macro avg       0.96      0.96      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.005
Current Num_Epochs:  10
Train accuracy: 0.9685901999473572
Validation accuracy: 0.9249146580696106
Test accuracy: 0.9251700639724731
Train Confusion Matrix:
[[646  15]
 [ 28 680]]
Validation Confusion Matrix:
[[130  11]
 [ 11 141]]
Test Confusion Matrix:
[[135  14]
 [  8 137]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97       661
           1       0.98      0.96      0.97       708

    accuracy                           0.97      1369
   macro avg       0.97      0.97      0.97      1369
weighted avg       0.97      0.97      0.97      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       141
           1       0.93      0.93      0.93       152

    accuracy                           0.92       293
   macro avg       0.92      0.92      

BiLSTM Training


AttentionLSTM Training


Current Num_Layers:  2
Current Dropout:  0.7
Current Learning Rate:  0.005
Current Num_Epochs:  25
Train accuracy: 0.9963477253913879
Validation accuracy: 0.9488054513931274
Test accuracy: 0.9387755393981934
Train Confusion Matrix:
[[658   3]
 [  2 706]]
Validation Confusion Matrix:
[[132   9]
 [  6 146]]
Test Confusion Matrix:
[[138  11]
 [  7 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       661
           1       1.00      1.00      1.00       708

    accuracy                           1.00      1369
   macro avg       1.00      1.00      1.00      1369
weighted avg       1.00      1.00      1.00      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.94      0.95       141
           1       0.94      0.96      0.95       152

    accuracy                           0.95       293
   macro avg       0.95      0.95      

BiLSTM Training


Epoch [7/50]:  91%|█████████ | 20/22 [00:04<00:00,  5.23it/s, loss=0.0769]

In [ ]:
results(model_LSTM)
results(model_BiLSTM)
results(model_AttentionLSTM)

Train accuracy: 0.9839298725128174
Validation accuracy: 0.9419795274734497
Test accuracy: 0.9455782175064087
Train Confusion Matrix:
[[659  11]
 [ 11 688]]
Validation Confusion Matrix:
[[127   7]
 [ 10 149]]
Test Confusion Matrix:
[[140   7]
 [  9 138]]
Train Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       670
           1       0.98      0.98      0.98       699

    accuracy                           0.98      1369
   macro avg       0.98      0.98      0.98      1369
weighted avg       0.98      0.98      0.98      1369

Validation Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       134
           1       0.96      0.94      0.95       159

    accuracy                           0.94       293
   macro avg       0.94      0.94      0.94       293
weighted avg       0.94      0.94      0.94       293

Test Classification Report:
 

In [ ]:
# Print the original comments, model predictions and actual labels
for i in range(5):
    print(f'Comment: {original_comments[i]}')
    print(f'Tokens: {tokens[i]}')
    print(f'Prediction: {model_predictions[i]}')
    print(f'Actual: {actual_labels[i]}')
    print('')


Comment: [CLS] love your song makes me happy [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
Tokens: tensor([ 101, 2293, 2115, 2299, 3084, 2033, 3407,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0])
Prediction: 0
Actual: 0

Comment: [CLS] is that tiger called'katty purry '? [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD]
Tokens: tensor([  101,  2003,  2008,  6816,  2170,  1005, 10645,  3723, 16405, 12244,
         1005,  1029,   102,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0])
Prediction: 0
Actual: 0

Comment: [CLS] sign up for free on tsu and start making money on social media add / follow me and ill add follow you!! http : / [SEP]
Tokens: tensor([  